# Generated by Django 3.0 on 2020-11-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('awaiting_approval', 'awaiting_approval'), ('approved', 'approved')], default='awaiting_approval', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
                ('cashback_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('cashback_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='resellers.Reseller')),
            ],
        ),
    ]
