# Generated by Django 3.0 on 2020-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('cpf', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome Completo')),
            ],
        ),
    ]
